#!/bin/sh

currentDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

install_dotfile() {
  local name="$1"
  local from="$currentDir/$name"
  local to="$HOME/$name"

  if [ ! -e $to ]; then
    ln -s $from $to
  fi
}
